/**
 * character/avatar domain — public API for SagaDrive avatar core contracts.
 * Location: src/domains/character/avatar/index.ts
 */
export type {
  AvatarCoreStatus,
  AvatarTraitFormat,
  CharacterTraitAssetRef,
  CharacterTraitGroup,
  CharacterTraitInstance,
  CharacterTraitManifest,
  RuntimeOverlay,
  TraitInstanceRole,
  TraitLifecyclePort,
} from './types';
export {
  assertDistinctInstanceIdentities,
  createTraitLifecycleRegistry,
  type TraitLifecycleRegistryOptions,
} from './trait-lifecycle-registry';
export {
  AVATAR_TRAIT_GROUP_IDS,
  isAvatarTraitGroupId,
  resolveEffectiveTraits,
  serializePersistedBaseTraits,
  type AvatarTraitGroupId,
  type BaseTraitSelection,
  type EffectiveTraitSelection,
  type RuntimeTraitOverlay,
} from './trait-layers';
export {
  AVATAR_TRAIT_SECTIONS,
  getTraitOption,
  isAllowedTraitId,
  listTraitOptionsForGroup,
  traitGroupLabel,
  type AvatarTraitOption,
  type AvatarTraitSection,
} from './trait-catalog';
export {
  AVATAR_IMPORT_ALLOWED_EXTENSIONS,
  AVATAR_IMPORT_MAX_BYTES,
  buildAvatarImportStoragePath,
  containsUnsafeExternalUriHint,
  earlyCheckAvatarImportFile,
  extensionFromFileName,
  formatFromExtension,
  sanitizeImportResultFromServer,
  sniffGlbContainer,
  validateAvatarImportBytes,
  type AvatarImportArtifact,
  type AvatarImportEarlyCheck,
  type AvatarImportExtension,
  type AvatarImportFormat,
  type AvatarImportUiStatus,
  type AvatarRigAnalysisStatus,
} from './avatar-import';
export {
  RIG_CONTRACT_VERSION,
  SAGA_DRIVE_HUMANOID_ANCHORS,
  SAGA_DRIVE_HUMANOID_BONES,
  capabilityFlagLabel,
  listMissingHumanoidBones,
  resolveAvatarRigCapabilities,
  summarizeRigAnalysisStatus,
  type AvatarRigAnalysisResult,
  type AvatarRigAnalysisUiStatus,
  type AvatarRigCapabilities,
  type AvatarRigCapabilityFlag,
  type SagaDriveHumanoidAnchorId,
  type SagaDriveHumanoidBoneId,
  type SagaDriveHumanoidRigV1,
} from './rig-contract';
export {
  AVATAR_MORPH_BODY_KEYS,
  AVATAR_MORPH_BODY_META,
  AVATAR_MORPH_FACE_KEYS,
  AVATAR_MORPH_FACE_META,
  AVATAR_MORPH_PARAM_META,
  MORPH_CONTRACT_VERSION,
  createDefaultAvatarMorphState,
  getAvatarMorphParamMeta,
  isAvatarMorphBodyKey,
  isAvatarMorphFaceKey,
  isAvatarMorphParamKey,
  legacySliderToMorph,
  mergeAvatarMorphPresets,
  migrateCharacterAvatarDtoToMorph,
  morphCapabilityFlagLabel,
  morphToLegacySlider,
  resolveAvatarMorphCapabilities,
  validateAvatarMorphInput,
  withAvatarMorphState,
  type AvatarMorphBodyKey,
  type AvatarMorphBodyValues,
  type AvatarMorphCapabilityFlag,
  type AvatarMorphColorsV1,
  type AvatarMorphFaceKey,
  type AvatarMorphFaceValues,
  type AvatarMorphParamGroup,
  type AvatarMorphParamKey,
  type AvatarMorphParamMeta,
  type AvatarMorphTraitSlotsV1,
  type AvatarMorphValidationResult,
  type SagaDriveAvatarMorphStateV1,
} from './morph-contract';
export {
  BASE_BODY_ASSET_VERSION,
  BASE_BODY_CAMERA_SAFE_BOUNDS,
  BASE_BODY_CONTRACT_VERSION,
  BASE_BODY_MATERIAL_SLOTS,
  BASE_BODY_SPECIES_PRESETS,
  BASE_BODY_TRAIT_SOCKETS,
  DEFAULT_BASE_BODY_FIT_RANGES,
  assertMorphFixtureCameraSafe,
  buildBaseBodyMorphFixtureCases,
  createCanonicalMorphTargetMap,
  createSagaDriveBaseBodyManifestV1,
  deriveSpeciesMorphState,
  getBaseBodySpeciesPreset,
  isBaseBodyCacheCompatible,
  listRequiredMorphTargetNames,
  resolveBaseBodyMorphCapabilities,
  type BaseBodyFitRange,
  type BaseBodyMaterialSlot,
  type BaseBodyMorphCapabilityReport,
  type BaseBodyMorphFixtureCase,
  type BaseBodyMorphTargetMap,
  type BaseBodyProvenance,
  type BaseBodySpeciesId,
  type BaseBodySpeciesPresetV1,
  type BaseBodyTraitSocket,
  type SagaDriveBaseBodyManifestV1,
} from './base-body-contract';
export {
  MTOON_MATERIAL_CLASSES,
  MTOON_PROFILE_VERSION,
  classifyMtoonMaterialClass,
  createSagaDriveMToonProfileV1,
  listMtoonMaterialClassIds,
  resolveMtoonPerformancePreset,
  resolveMtoonRenderPath,
  type MtoonLightRig,
  type MtoonMaterialClass,
  type MtoonMaterialClassProfile,
  type MtoonOutlinePolicy,
  type MtoonPerformancePreset,
  type MtoonPerformanceProfile,
  type MtoonRenderPath,
  type MtoonStyleCompatibility,
  type SagaDriveMToonProfileV1,
} from './mtoon-profile';
export {
  FIT_RANGE_CONTRACT_VERSION,
  clampMorphToFitRange,
  createDefaultTraitFitRange,
  listPrimaryFitMorphKeys,
  resolveAvatarFitCompatibility,
  type AvatarFitCompatibilityResult,
  type AvatarFitMorphBound,
  type AvatarFitRangeV1,
  type AvatarFitStatus,
} from './fit-range-contract';
export {
  AVATAR_SAVE_EXPORT_MAX_BYTES,
  AVATAR_SAVE_EXPORT_VERSION,
  assertExportPayloadSafe,
  buildAvatarExportStoragePath,
  buildAvatarSaveExportPayload,
  encodeAvatarExportGlb,
  type AvatarSaveExportArtifact,
  type AvatarSaveExportPayloadV1,
  type AvatarSaveExportUiStatus,
} from './avatar-save-export';
export {
  ANIMATION_CONTRACT_VERSION,
  AVATAR_ANIMATION_ACTIONS,
  AVATAR_ANIMATION_CATALOG,
  animationActionLabelDe,
  getAnimationCatalogEntry,
  isAllowlistedAnimationClipId,
  resolveAnimationCrossfadeSeconds,
  resolveAvatarAnimationSupport,
  type AvatarAnimationActionId,
  type AvatarAnimationClipCatalogEntry,
  type AvatarAnimationSupportResult,
} from './animation-contract';
export {
  FACIAL_BLINK_KEY,
  FACIAL_CANONICAL_KEYS,
  FACIAL_CONTRACT_VERSION,
  FACIAL_EMOTION_KEYS,
  FACIAL_VISEME_KEYS,
  FACIAL_VRM_ALIASES,
  applyFacialLayerUpdate,
  clampFacialWeight,
  createNeutralFacialWeights,
  facialKeyLabelDe,
  facialLayerForKey,
  resolveFacialAvailability,
  type FacialAvailability,
  type FacialBlinkKey,
  type FacialCanonicalKey,
  type FacialEmotionKey,
  type FacialLayer,
  type FacialVisemeKey,
} from './facial-contract';
export {
  CONTENT_PACK_VERSION,
  CONTENT_PACK_V1_ASSETS,
  CONTENT_PACK_V1_MINIMUMS,
  assertContentPackV1Minimums,
  countContentPackByCategory,
  getContentPackAsset,
  listContentPackAssets,
  type ContentPackAssetV1,
  type ContentPackCategory,
  type ContentPackLicense,
  type ContentPackSetting,
} from './content-pack-v1';
export {
  MESHY_AVATAR_JOB_CONTRACT_VERSION,
  MESHY_AVATAR_PROMPT_MAX_CHARS,
  MESHY_AVATAR_PROMPT_MIN_CHARS,
  assertNoCapabilityFromProviderStatus,
  buildMeshyAvatarIdempotencyKey,
  mapServerStatusToUi,
  validateMeshyAvatarPrompt,
  type AvatarRiggingProvider,
  type MeshyAvatarJobServerStatus,
  type MeshyAvatarJobSnapshot,
  type MeshyAvatarJobUiStatus,
} from './meshy-avatar-job';
export {
  AVATAR_SOURCES,
  AVATAR_SOURCE_CONTRACT_VERSION,
  AVATAR_SOURCE_OPTIONS,
  LEGACY_AVATAR_PROVIDER,
  avatarSourceMeta,
  describeAvatarSourceCapabilities,
  evaluateAvatarSourceSwitch,
  isAvatarSource,
  resolveAvatarSource,
  type AvatarSource,
  type AvatarSourceOptionMeta,
  type AvatarSourceSwitchDecision,
} from './avatar-source';
