/**
 * character/avatar domain — public API for SagaDrive avatar core contracts.
 * Location: src/domains/character/avatar/index.ts
 */
export type {
  AvatarCoreStatus,
  AvatarTraitFormat,
  CharacterTraitAssetRef,
  CharacterTraitGroup,
  CharacterTraitInstance,
  CharacterTraitManifest,
  RuntimeOverlay,
  TraitInstanceRole,
  TraitLifecyclePort,
} from './types';
export {
  assertDistinctInstanceIdentities,
  createTraitLifecycleRegistry,
  type TraitLifecycleRegistryOptions,
} from './trait-lifecycle-registry';
export {
  AVATAR_TRAIT_GROUP_IDS,
  isAvatarTraitGroupId,
  resolveEffectiveTraits,
  serializePersistedBaseTraits,
  type AvatarTraitGroupId,
  type BaseTraitSelection,
  type EffectiveTraitSelection,
  type RuntimeTraitOverlay,
} from './trait-layers';
export {
  AVATAR_TRAIT_SECTIONS,
  getTraitOption,
  isAllowedTraitId,
  listTraitOptionsForGroup,
  traitGroupLabel,
  type AvatarTraitOption,
  type AvatarTraitSection,
} from './trait-catalog';
export {
  AVATAR_IMPORT_ALLOWED_EXTENSIONS,
  AVATAR_IMPORT_MAX_BYTES,
  buildAvatarImportStoragePath,
  containsUnsafeExternalUriHint,
  earlyCheckAvatarImportFile,
  extensionFromFileName,
  formatFromExtension,
  sanitizeImportResultFromServer,
  sniffGlbContainer,
  validateAvatarImportBytes,
  type AvatarImportArtifact,
  type AvatarImportEarlyCheck,
  type AvatarImportExtension,
  type AvatarImportFormat,
  type AvatarImportUiStatus,
  type AvatarRigAnalysisStatus,
} from './avatar-import';
export {
  AVATAR_IMPORT_GLB_SPEC_HELP_HREF,
  AVATAR_IMPORT_GLB_SPEC_HELP_LABEL_DE,
  IMPORT_ORIGINAL_FLOW_CONTRACT_VERSION,
  IMPORT_ORIGINAL_FLOW_STATUSES,
  assertImportOriginalFlowInvariants,
  buildImportAnalysisSummary,
  buildImportOriginalKeepSeed,
  isImportOriginalFlowStatus,
  morphEvidenceFromImportAnalysis,
  resolveImportFlowStatusFromAnalysis,
  type ImportAnalysisSummaryV1,
  type ImportOriginalFlowStatus,
  type ImportOriginalKeepSeedV1,
} from './import-original-flow-v1';
export {
  IDENTITY_TRANSFER_APPROACH_IDS,
  IDENTITY_TRANSFER_GOLDEN_FIXTURE_IDS,
  IDENTITY_TRANSFER_GOLDEN_MATRIX_V1,
  IDENTITY_TRANSFER_IDENTITY_FIDELITY_THRESHOLD,
  IDENTITY_TRANSFER_SCORE_WEIGHTS,
  IDENTITY_TRANSFER_SPIKE_CONTRACT_VERSION,
  assertIdentityTransferSpikeInvariants,
  buildIdentityTransferConversionPlan,
  listScoresForApproach,
  meanAggregate,
  meanIdentityFidelity,
  resolveIdentityTransferDecision,
  selectTransferPipelineForFixture,
  weightedAggregate,
  type IdentityTransferApproachId,
  type IdentityTransferApproachScoreV1,
  type IdentityTransferConversionPlanV1,
  type IdentityTransferDecisionV1,
  type IdentityTransferGoldenFixtureId,
  type IdentityTransferScoreAxis,
  type IdentityTransferScoreRow,
} from './identity-transfer-spike-v1';
export {
  BODY_CONVERSION_FLOW_CONTRACT_VERSION,
  BODY_CONVERSION_TARGET_FAMILIES,
  assertBodyConversionFlowInvariants,
  isBodyConversionTargetFamily,
  listBodyConversionFamilyOptions,
  planBodyConversion,
  type BodyConversionFamilyOptionV1,
  type BodyConversionRequestV1,
  type BodyConversionResultV1,
  type BodyConversionStatus,
  type BodyConversionTargetFamily,
} from './body-conversion-flow-v1';
export {
  RIG_CONTRACT_VERSION,
  SAGA_DRIVE_HUMANOID_ANCHORS,
  SAGA_DRIVE_HUMANOID_BONES,
  capabilityFlagLabel,
  listMissingHumanoidBones,
  resolveAvatarRigCapabilities,
  summarizeRigAnalysisStatus,
  type AvatarRigAnalysisResult,
  type AvatarRigAnalysisUiStatus,
  type AvatarRigCapabilities,
  type AvatarRigCapabilityFlag,
  type SagaDriveHumanoidAnchorId,
  type SagaDriveHumanoidBoneId,
  type SagaDriveHumanoidRigV1,
} from './rig-contract';
export {
  AVATAR_RIG_CAPABILITY_FLAGS_V2,
  AVATAR_RIG_PROFILE_KINDS_V2,
  AVATAR_SAFE_CUSTOM_ANCHORS_V2,
  AVATAR_SEMANTIC_ANCHORS_V2,
  CUSTOM_CREATURE_GOLDEN_FIXTURE_IDS,
  RIG_CAPABILITY_CONTRACT_V2_VERSION,
  assertCustomCreatureContractInvariants,
  buildHumanoidRigV1FromEvidence,
  capabilityFlagLabelV2,
  deriveSemanticAnchorsFromHumanoidBones,
  listCustomCreatureGoldenFixtures,
  mapHumanoidRigV1ToProfile,
  resolveAvatarRigCapabilitiesV2,
  resolveGoldenFixtureCapabilities,
  summarizeCapabilitiesStatusV2,
  type AvatarCustomCreatureProfileV2,
  type AvatarHumanoidProfileV2,
  type AvatarRigAnalysisUiStatusV2,
  type AvatarRigCapabilitiesV2,
  type AvatarRigCapabilityFlagV2,
  type AvatarRigProfileKindV2,
  type AvatarRigProfileV2,
  type AvatarSemanticAnchorIdV2,
  type AvatarSkeletonEvidenceV2,
  type CustomCreatureGoldenFixtureId,
  type CustomCreatureGoldenFixtureV2,
} from './rig-capability-contract-v2';
export {
  AVATAR_MORPH_BODY_KEYS,
  AVATAR_MORPH_BODY_META,
  AVATAR_MORPH_FACE_KEYS,
  AVATAR_MORPH_FACE_META,
  AVATAR_MORPH_PARAM_META,
  MORPH_CONTRACT_VERSION,
  createDefaultAvatarMorphState,
  getAvatarMorphParamMeta,
  isAvatarMorphBodyKey,
  isAvatarMorphFaceKey,
  isAvatarMorphParamKey,
  legacySliderToMorph,
  mergeAvatarMorphPresets,
  migrateCharacterAvatarDtoToMorph,
  morphCapabilityFlagLabel,
  morphToLegacySlider,
  resolveAvatarMorphCapabilities,
  validateAvatarMorphInput,
  withAvatarMorphState,
  type AvatarMorphBodyKey,
  type AvatarMorphBodyValues,
  type AvatarMorphCapabilityFlag,
  type AvatarMorphColorsV1,
  type AvatarMorphFaceKey,
  type AvatarMorphFaceValues,
  type AvatarMorphParamGroup,
  type AvatarMorphParamKey,
  type AvatarMorphParamMeta,
  type AvatarMorphTraitSlotsV1,
  type AvatarMorphValidationResult,
  type SagaDriveAvatarMorphStateV1,
} from './morph-contract';
export {
  BASE_BODY_ASSET_VERSION,
  BASE_BODY_CAMERA_SAFE_BOUNDS,
  BASE_BODY_CONTRACT_VERSION,
  BASE_BODY_MATERIAL_SLOTS,
  BASE_BODY_SPECIES_PRESETS,
  BASE_BODY_TRAIT_SOCKETS,
  DEFAULT_BASE_BODY_FIT_RANGES,
  assertMorphFixtureCameraSafe,
  buildBaseBodyMorphFixtureCases,
  createCanonicalMorphTargetMap,
  createSagaDriveBaseBodyManifestV1,
  deriveSpeciesMorphState,
  getBaseBodySpeciesPreset,
  isBaseBodyCacheCompatible,
  listRequiredMorphTargetNames,
  resolveBaseBodyMorphCapabilities,
  type BaseBodyFitRange,
  type BaseBodyMaterialSlot,
  type BaseBodyMorphCapabilityReport,
  type BaseBodyMorphFixtureCase,
  type BaseBodyMorphTargetMap,
  type BaseBodyProvenance,
  type BaseBodySpeciesId,
  type BaseBodySpeciesPresetV1,
  type BaseBodyTraitSocket,
  type SagaDriveBaseBodyManifestV1,
} from './base-body-contract';
export {
  CANONICAL_BODY_ASSET_IDS,
  CANONICAL_BODY_FAMILIES_CONTRACT_VERSION,
  CANONICAL_BODY_FAMILY_IDS,
  CANONICAL_BODY_REGIONS,
  LEGACY_BASE_BODY_ASSET_ID,
  allowlistedCanonicalBodyPaths,
  assertCanonicalBodyPublishable,
  createCanonicalBodyFamilyManifest,
  isCanonicalBodyFamilyId,
  listCanonicalBodyFamilyManifests,
  resolveCanonicalBodyFamilyId,
  toSagaDriveBaseBodyManifest,
  type CanonicalBodyAssetId,
  type CanonicalBodyFamilyId,
  type CanonicalBodyFamilyManifestV1,
  type CanonicalBodyPublishGateResult,
  type CanonicalBodyRegion,
} from './canonical-body-families-v1';
export {
  MTOON_MATERIAL_CLASSES,
  MTOON_PROFILE_VERSION,
  classifyMtoonMaterialClass,
  createSagaDriveMToonProfileV1,
  listMtoonMaterialClassIds,
  resolveMtoonPerformancePreset,
  resolveMtoonRenderPath,
  type MtoonLightRig,
  type MtoonMaterialClass,
  type MtoonMaterialClassProfile,
  type MtoonOutlinePolicy,
  type MtoonPerformancePreset,
  type MtoonPerformanceProfile,
  type MtoonRenderPath,
  type MtoonStyleCompatibility,
  type SagaDriveMToonProfileV1,
} from './mtoon-profile';
export {
  FIT_RANGE_CONTRACT_VERSION,
  clampMorphToFitRange,
  createDefaultTraitFitRange,
  listPrimaryFitMorphKeys,
  resolveAvatarFitCompatibility,
  type AvatarFitCompatibilityResult,
  type AvatarFitMorphBound,
  type AvatarFitRangeV1,
  type AvatarFitStatus,
} from './fit-range-contract';
export {
  AVATAR_SAVE_EXPORT_MAX_BYTES,
  AVATAR_SAVE_EXPORT_VERSION,
  assertExportPayloadSafe,
  buildAvatarExportStoragePath,
  buildAvatarSaveExportPayload,
  encodeAvatarExportGlb,
  type AvatarSaveExportArtifact,
  type AvatarSaveExportPayloadV1,
  type AvatarSaveExportUiStatus,
} from './avatar-save-export';
export {
  ANIMATION_CONTRACT_VERSION,
  AVATAR_ANIMATION_ACTIONS,
  AVATAR_ANIMATION_CATALOG,
  animationActionLabelDe,
  getAnimationCatalogEntry,
  isAllowlistedAnimationClipId,
  resolveAnimationCrossfadeSeconds,
  resolveAvatarAnimationSupport,
  type AvatarAnimationActionId,
  type AvatarAnimationClipCatalogEntry,
  type AvatarAnimationSupportResult,
} from './animation-contract';
export {
  FACIAL_BLINK_KEY,
  FACIAL_CANONICAL_KEYS,
  FACIAL_CONTRACT_VERSION,
  FACIAL_EMOTION_KEYS,
  FACIAL_VISEME_KEYS,
  FACIAL_VRM_ALIASES,
  applyFacialLayerUpdate,
  clampFacialWeight,
  createNeutralFacialWeights,
  facialKeyLabelDe,
  facialLayerForKey,
  resolveFacialAvailability,
  type FacialAvailability,
  type FacialBlinkKey,
  type FacialCanonicalKey,
  type FacialEmotionKey,
  type FacialLayer,
  type FacialVisemeKey,
} from './facial-contract';
export {
  AVATAR_V2_ANATOMIES,
  AVATAR_V2_BODY_COMPATIBILITIES,
  AVATAR_V2_BODY_FAMILIES,
  AVATAR_V2_COMPOSITION_CONTRACT_VERSION,
  AVATAR_V2_MODULARITIES,
  AVATAR_V2_SOURCES,
  assertCompositionCapabilitiesNotFromSource,
  assertSpeciesOrthogonalToBodyFamily,
  compositionFromCharacterAvatarDto,
  isAvatarV2Anatomy,
  isAvatarV2BodyCompatibility,
  isAvatarV2BodyFamily,
  isAvatarV2Modularity,
  isAvatarV2Source,
  parseAvatarV2CompositionFields,
  toAvatarV2Source,
  type AvatarV2Anatomy,
  type AvatarV2BodyCompatibility,
  type AvatarV2BodyFamily,
  type AvatarV2Composition,
  type AvatarV2Modularity,
  type AvatarV2Source,
} from './composition-contract-v2';
export {
  AVATAR_EDITOR_SURFACE_IDS,
  AVATAR_EDITOR_SURFACE_RESOLVER_VERSION,
  resolveAvatarEditorSurfaces,
  resolveEditorSurfacesFromAvatarState,
  resolveMorphEvidenceForComposition,
  type AvatarEditorCapabilityStatus,
  type AvatarEditorSurfaceId,
  type AvatarEditorSurfaceMap,
  type AvatarEditorSurfaces,
  type AvatarMorphEvidenceInput,
  type AvatarMorphEvidenceResolution,
} from './editor-surface-resolver-v1';
export {
  MODULAR_AVATAR_GLB_CONTRACT_VERSION,
  MODULAR_AVATAR_GLB_NODE_ROLES,
  MODULAR_AVATAR_GLB_ROLE_SLOT_HINTS,
  MODULAR_AVATAR_GLB_SLOTS,
  MODULAR_AVATAR_GLB_STATUSES,
  isModularAvatarGlbNodeRole,
  isModularAvatarGlbSlot,
  parseModularAvatarGlbExtras,
  validateModularAvatarGlbNodes,
  type ModularAvatarGlbExtrasV1,
  type ModularAvatarGlbNodeDescriptor,
  type ModularAvatarGlbNodeRole,
  type ModularAvatarGlbSlot,
  type ModularAvatarGlbStatus,
  type ModularAvatarGlbValidationIssue,
  type ModularAvatarGlbValidationResult,
} from './modular-glb-contract-v1';
export {
  AVATAR_ARTIFACT_ANALYSIS_STATUSES,
  AVATAR_ARTIFACT_CONTRACT_VERSION,
  AVATAR_ARTIFACT_FORMATS,
  AVATAR_ARTIFACT_MATERIALIZATION_STATUSES,
  assertCanActivateAvatarArtifact,
  assertLogicalAvatarArtifactAssetKey,
  assertOwnerScopedStoragePath,
  buildAvatarArtifactAssetKey,
  createInMemoryAvatarArtifactRepository,
  isAvatarArtifactAnalysisStatus,
  isAvatarArtifactFormat,
  isAvatarArtifactMaterializationStatus,
  mapGenerateJobToArtifactInput,
  mapImportAssetToArtifactInput,
  mapTemplateToArtifactInput,
  markAvatarArtifactMaterializationFailed,
  materializeAvatarArtifact,
  originFromLegacyAvatarSource,
  sanitizeClientAvatarArtifactMutation,
  type AvatarArtifactActivateResult,
  type AvatarArtifactAnalysisStatus,
  type AvatarArtifactAssetRef,
  type AvatarArtifactFormat,
  type AvatarArtifactMaterializeInput,
  type AvatarArtifactMaterializationStatus,
  type AvatarArtifactRepository,
  type AvatarArtifactSourceRef,
  type AvatarArtifactV2,
} from './avatar-artifact-contract-v2';
export {
  AVATAR_STRUCTURE_ANALYSIS_BOUNDS,
  AVATAR_STRUCTURE_ANALYSIS_STATUSES,
  AVATAR_STRUCTURE_ANALYZER_CONTRACT_VERSION,
  AVATAR_STRUCTURE_MODULARITY_KINDS,
  analyzeAvatarStructureFromEvidence,
  authoritativeAnalyzeAvatarStructure,
  isAvatarStructureModularityKind,
  mapStructureModularityToComposition,
  previewAnalyzeAvatarStructure,
  sanitizeClientStructureAnalysisClaim,
  structureAnalysisCompatibleWithComposition,
  type AvatarStructureAnalysisResultV2,
  type AvatarStructureAnalysisStatus,
  type AvatarStructureEvidence,
  type AvatarStructureMeshEvidence,
  type AvatarStructureModularityKind,
  type AvatarStructureNodeEvidence,
  type AvatarStructureRoleHit,
} from './avatar-structure-analyzer-v2';
export {
  BODY_FAMILY_COMPATIBILITY_THRESHOLD,
  BODY_FAMILY_REFERENCE_PROFILES_V1,
  BODY_PROFILE_CONTRACT_VERSION,
  BODY_PROFILE_FAMILY_IDS,
  BODY_PROFILE_VALIDATION_STATUSES,
  FAMILY_COMPATIBILITY_STATUSES,
  bodyProfileFromMetricLengths,
  createBodyProfileV1,
  getBodyFamilyReferenceProfile,
  isBodyProfileFamilyId,
  resolveFamilyCompatibility,
  scoreBodyProfileSimilarity,
  validateBodyProfileProportions,
  type BodyFamilyReferenceProfileV1,
  type BodyProfileFamilyId,
  type BodyProfileProportionsV1,
  type BodyProfileV1,
  type BodyProfileValidationStatus,
  type FamilyCompatibilityResultV1,
  type FamilyCompatibilityStatus,
  type FamilyScoreV1,
  type HumanoidMetricLengthsV1,
} from './body-profile-contract-v1';
export {
  ASSET_AUTHORING_CANDIDATE_STATUSES,
  ASSET_AUTHORING_CONTRACT_VERSION,
  ASSET_AUTHORING_KINDS,
  ASSET_AUTHORING_LICENSE_KINDS,
  ASSET_AUTHORING_STAGES,
  ASSET_AUTHORING_STYLE_TAGS,
  DEFAULT_ASSET_AUTHORING_GOLDEN_CRITERIA,
  assertAuthoringUsesGenerationContract,
  assertCanPublishAuthoringAsset,
  createAssetAuthoringManifest,
  isAssetAuthoringKind,
  selectAssetAuthoringCandidate,
  validateAssetAuthoringCandidate,
  type AssetAuthoringCandidateEvidenceV1,
  type AssetAuthoringCandidateStatus,
  type AssetAuthoringCandidateV1,
  type AssetAuthoringGoldenCriteriaV1,
  type AssetAuthoringKind,
  type AssetAuthoringLicenseKind,
  type AssetAuthoringManifestV1,
  type AssetAuthoringProvenanceV1,
  type AssetAuthoringStage,
  type AssetAuthoringStyleTag,
  type AssetAuthoringValidationIssue,
  type AssetAuthoringValidationResultV1,
} from './asset-authoring-contract-v1';
export {
  DEFAULT_FACE_TRACKING_LIMITS,
  FACE_TRACKING_CONTRACT_VERSION,
  FACE_TRACKING_QUALITY_PROFILES,
  FACE_TRACKING_STATUSES,
  assertFaceTrackingDriveLocalOnly,
  clampAngle,
  clampUnit,
  createEmptyFaceTrackingSample,
  faceTrackingStatusLabelDe,
  isFaceTrackingStatus,
  mapFaceTrackingSample,
  resolveFaceTrackingFpsCap,
  resolveFaceTrackingQualityProfile,
  selectPrimaryFaceIndex,
  smoothFaceTrackingDrive,
  type FaceTrackingDrive,
  type FaceTrackingHeadPose,
  type FaceTrackingLimits,
  type FaceTrackingQualityProfile,
  type FaceTrackingQualityProfileId,
  type FaceTrackingSample,
  type FaceTrackingStatus,
} from './face-tracking-contract';
export {
  CONTENT_PACK_VERSION,
  CONTENT_PACK_V1_ASSETS,
  CONTENT_PACK_V1_MINIMUMS,
  assertContentPackV1Minimums,
  countContentPackByCategory,
  getContentPackAsset,
  listContentPackAssets,
  type ContentPackAssetV1,
  type ContentPackCategory,
  type ContentPackLicense,
  type ContentPackSetting,
} from './content-pack-v1';
export {
  MESHY_AVATAR_JOB_CONTRACT_VERSION,
  MESHY_AVATAR_IMAGE_MAX_BYTES,
  MESHY_AVATAR_IMAGE_PLACEHOLDER_PROMPT,
  MESHY_AVATAR_CREDITS_IMAGE_TEXTURED,
  MESHY_AVATAR_CREDITS_IMAGE_TEXTURED_4K,
  MESHY_AVATAR_CREDITS_TEXT_PREVIEW,
  MESHY_AVATAR_PROMPT_MAX_CHARS,
  MESHY_AVATAR_PROMPT_MIN_CHARS,
  MESHY_AVATAR_POLL_STALE_MS,
  assertNoCapabilityFromProviderStatus,
  buildMeshyAvatarIdempotencyKey,
  estimateMeshyAvatarCredits,
  estimateMeshyAvatarCreditsForSettings,
  isMeshyAvatarJobBusy,
  mapServerStatusToUi,
  monotonicMeshyProgress,
  resolveMeshyAvatarJobPrompt,
  validateMeshyAvatarImageDataUri,
  validateMeshyAvatarPrompt,
  validateMeshyAvatarTexturePrompt,
  type MeshyAvatarGenerationMode,
  type MeshyAvatarPollHealth,
  type MeshyAvatarRiggingHint,
  type MeshyAvatarJobServerStatus,
  type MeshyAvatarJobSnapshot,
  type MeshyAvatarJobUiStatus,
} from './meshy-avatar-job';
export {
  AVATAR_3D_GENERATION_CONTRACT_VERSION,
  AVATAR_3D_GENERATION_PROVIDER_IDS,
  MESHY_CAPABILITY,
  MESHY_PRESET_FAST,
  MESHY_PRESET_MAXIMUM,
  MESHY_PRESET_RECOMMENDED,
  MESHY_PROVIDER_ID,
  buildGenerationRecord,
  defaultPresetForProvider,
  getPreset,
  getProviderCapability,
  isAvatar3dGenerationProviderId,
  isPresetDirty,
  listAvatar3dGenerationProviders,
  mapProviderFailureToGenerationError,
  mapSettingsToMeshyImageTo3d,
  presetLabelDe,
  settingsEqual,
  summarizeSettingsDe,
  validateGenerationSettings,
  type Avatar3dGenerationMode,
  type Avatar3dGenerationProviderId,
  type Avatar3dGenerationRecord,
  type Avatar3dGenerationSettings,
  type GenerationError,
  type GenerationPresetDefinition,
  type GenerationPresetId,
  type ProviderCapabilityDefinition,
} from './generation';
export {
  AVATAR_SOURCES,
  AVATAR_SOURCE_CONTRACT_VERSION,
  AVATAR_SOURCE_OPTIONS,
  LEGACY_AVATAR_PROVIDER,
  avatarSourceMeta,
  describeAvatarSourceCapabilities,
  evaluateAvatarSourceSwitch,
  isAvatarSource,
  resolveAvatarSource,
  type AvatarSource,
  type AvatarSourceOptionMeta,
  type AvatarSourceSwitchDecision,
} from './avatar-source';
export {
  AVATAR_RENDER_MODES,
  AVATAR_SURFACE_IDS,
  AVATAR_SURFACE_MAX_LIVE_3D,
  SHARED_AVATAR_SURFACE_CONTRACT_VERSION,
  assertNoInventoryInSurfaceRef,
  defaultRenderModeForSurface,
  isAvatarRenderMode,
  isAvatarSurfaceId,
  resolveAvatarSurfaceView,
  type AvatarRenderMode,
  type AvatarSurfaceId,
  type AvatarSurfaceRef,
  type AvatarSurfaceViewModel,
} from './shared-avatar-surface';
export {
  EQUIPMENT_ATTACHMENT_KINDS,
  EQUIPMENT_HIDE_REGIONS,
  EQUIPMENT_VISUAL_CONTRACT_VERSION,
  EQUIPMENT_VISUAL_STATUSES,
  clampEquipmentTransform,
  createAvatarEquipmentBinding,
  createInMemoryAvatarEquipmentBindingRepository,
  isEquipmentAttachmentKind,
  isEquipmentHideRegion,
  projectInventoryEquipmentVisuals,
  validateAvatarEquipmentBinding,
  type AvatarEquipmentBinding,
  type AvatarEquipmentBindingRepository,
  type AvatarEquipmentLocalTransform,
  type AvatarEquipmentVisual,
  type AvatarEquipmentVisualProjection,
  type EquipmentAttachmentKind,
  type EquipmentHideRegion,
  type EquipmentVisualStatus,
} from './equipment-visual-contract';
export {
  RIGID_EQUIPMENT_PLAN_VERSION,
  planRigidEquipmentAttaches,
  type RigidEquipmentAttachOp,
  type RigidEquipmentPlan,
} from './rigid-equipment-plan';
export {
  ITEM_AVATAR_FIT_DEFAULTS_VERSION,
  defaultAnchorForItemType,
  defaultAnchorForMiscEquip,
  defaultRigidFitTransform,
  resolveWorkbenchDefaultAnchor,
} from './item-avatar-fit-defaults';
export {
  RIGGING_JOB_STATUSES,
  RIGGING_MODES,
  RIGGING_PROVIDER_CONTRACT_VERSION,
  RIGGING_PROVIDER_IDS,
  assertLogicalRiggingAssetKey,
  assertRiggingCapabilitiesPending,
  buildRiggingIdempotencyKey,
  createMockMeshyRiggingProvider,
  createMockSkinTokensRiggingProvider,
  selectDefaultRiggingProvider,
  type AvatarRiggingJobSnapshot,
  type AvatarRiggingJobStatus,
  type AvatarRiggingMode,
  type AvatarRiggingProvider,
  type AvatarRiggingProviderId,
  type AvatarRiggingSubmitInput,
} from './rigging-provider-contract';
export {
  SKINNED_WEARABLE_PLAN_VERSION,
  extractStarterWearableIdFromAssetKey,
  mapFitToSkinnedUiStatus,
  planSkinnedWearableAttaches,
  type SkinnedWearableAttachOp,
  type SkinnedWearablePlan,
  type SkinnedWearableUiStatus,
} from './skinned-wearable-plan';
export {
  BODY_FAMILY_VARIANT_RESOLVER_VERSION,
  isBodyFamilyVariantReady,
  resolveBodyFamilyWearableVariant,
  type BodyFamilyVariantResolveInput,
  type BodyFamilyVariantResolveResult,
  type BodyFamilyVariantResolveStatus,
} from './body-family-variant-resolver-v1';
export {
  BODY_REGION_MASK_CONTRACT_VERSION,
  BodyRegionMaskRegistry,
  type BodyRegionMaskDelta,
  type BodyRegionMaskSnapshot,
} from './body-region-mask-v1';

export {
  SPECIES_DEFAULT_BODY_FAMILY,
  SPECIES_TEMPLATE_PACK_CONTRACT_VERSION,
  SPECIES_TEMPLATE_PACK_VERSION,
  assertSpeciesTemplatePackComplete,
  createSpeciesTemplateV1,
  listSpeciesTemplateIds,
  listSpeciesTemplatePickerItems,
  listSpeciesTemplatesV1,
  type SpeciesTemplatePickerItemV1,
  type SpeciesTemplateV1,
} from './species-template-pack-v1';
export {
  DEFAULT_TEMPLATE_BASIC_OUTFIT_IDS,
  SPECIES_TEMPLATE_INGRESS_CONTRACT_VERSION,
  applySpeciesTemplateIngress,
  assertTemplateCreatorFlowInvariants,
  listTemplateCreatorPickerItems,
  parseSpeciesTemplatePersistenceId,
  projectTemplateBasicOutfitVisuals,
  speciesTemplatePersistenceId,
  type SpeciesTemplateEditorSeedV1,
} from './species-template-ingress-v1';
export {
  STARTER_WARDROBE_CONTRACT_VERSION,
  STARTER_WARDROBE_PACK_VERSION,
  STARTER_WEARABLE_IDS,
  STARTER_WEARABLE_SLOTS,
  assertStarterWardrobeComplete,
  createStarterWearableManifest,
  getStarterWearableManifest,
  isStarterWearableId,
  listAllowlistedStarterWearablePaths,
  listGoldenFitMatrixEntries,
  listStarterWearableManifests,
  resolveStarterWearableFit,
  resolveStarterWearableFitForSpecies,
  restoreRegionsAfterUnequip,
  type ResolvedStarterWearableFitV1,
  type StarterWearableFamilyVariantV1,
  type StarterWearableFitStatus,
  type StarterWearableHideRule,
  type StarterWearableId,
  type StarterWearableManifestV1,
  type StarterWearableSlot,
} from './starter-wardrobe-manifest-v1';
