/**
 * starting-templates catalog — ten Level-1 builds from #465 design (#463).
 * Location: src/domains/rules/sagadrive/starting-templates/catalog.ts
 */
import {
  createEmptySagaDriveSkillRanks,
  type SagaDriveSkillKey,
} from '../character-creation';
import type { SagaDriveStartingTemplate } from './types';

function freeRanks(
  partial: Partial<Record<SagaDriveSkillKey, number>>,
): ReturnType<typeof createEmptySagaDriveSkillRanks> {
  const ranks = createEmptySagaDriveSkillRanks();
  for (const [key, value] of Object.entries(partial) as [SagaDriveSkillKey, number][]) {
    ranks[key] = value;
  }
  return ranks;
}

function bgSpec(skill: SagaDriveSkillKey, name: string) {
  return {
    skill,
    name,
    source: 'background' as const,
    acquiredAtLevel: 1,
  };
}

/**
 * Canonical V1 catalog — values must match `.qa/design/character-starting-templates-v1.md`.
 */
export const sagaDriveStartingTemplates: readonly SagaDriveStartingTemplate[] = [
  {
    key: 'berserker',
    labelDe: 'Berserker / Berserkerin',
    playstyleDe: 'Nahkämpfer mit roher Kraft: Du gehst voran, hältst Druck und brichst Linien im Körperkontakt.',
    archetype: 'fighter',
    essence: 'physical',
    attributes: {
      strength: 4,
      dexterity: 3,
      endurance: 3,
      mind: 1,
      perception: 2,
      charisma: 2,
    },
    backgroundTemplateId: 'sport-competition',
    freeSkillRanks: freeRanks({
      melee: 2,
      intimidation: 2,
      athletics: 1,
      awareness: 1,
      acrobatics: 1,
    }),
    backgroundSkillPoints: { athletics: 2 },
    archetypeTrainingSkill: 'melee',
    backgroundSpecialization: bgSpec('athletics', 'Kraftakt'),
  },
  {
    key: 'vanguard',
    labelDe: 'Vanguard',
    playstyleDe: 'Disziplinierter Soldat auf Distanz: Du hältst die Linie mit Feuer, Ausdauer und Systemen.',
    archetype: 'fighter',
    essence: 'technological',
    attributes: {
      strength: 3,
      dexterity: 2,
      endurance: 4,
      mind: 3,
      perception: 2,
      charisma: 1,
    },
    backgroundTemplateId: 'soldier',
    freeSkillRanks: freeRanks({
      athletics: 2,
      intimidation: 2,
      melee: 2,
      awareness: 1,
    }),
    backgroundSkillPoints: { ranged: 2 },
    archetypeTrainingSkill: 'ranged',
    backgroundSpecialization: bgSpec('ranged', 'Schusswaffen'),
  },
  {
    key: 'mage',
    labelDe: 'Zauberer / Zaubererin',
    playstyleDe: 'Akademischer Mystiker: Du liest Okkultes, analysierst und greifst über Wissen und Geist ein.',
    archetype: 'thinker',
    essence: 'spiritual',
    attributes: {
      strength: 1,
      dexterity: 2,
      endurance: 2,
      mind: 4,
      perception: 3,
      charisma: 3,
    },
    backgroundTemplateId: 'academy-research',
    freeSkillRanks: freeRanks({
      investigation: 2,
      awareness: 2,
      persuasion: 2,
      insight: 1,
    }),
    backgroundSkillPoints: { knowledge: 2 },
    archetypeTrainingSkill: 'knowledge',
    backgroundSpecialization: bgSpec('knowledge', 'Okkultes'),
  },
  {
    key: 'technomancer',
    labelDe: 'Technomant / Technomantin',
    playstyleDe: 'Tech-Denker und Archivar: Du knackst Systeme, folgst Spuren und wirkst über Technik statt Ritual.',
    archetype: 'thinker',
    essence: 'technological',
    attributes: {
      strength: 1,
      dexterity: 3,
      endurance: 2,
      mind: 4,
      perception: 3,
      charisma: 2,
    },
    backgroundTemplateId: 'academy-research',
    freeSkillRanks: freeRanks({
      technology: 2,
      investigation: 2,
      knowledge: 1,
      awareness: 1,
      sleight: 1,
    }),
    backgroundSkillPoints: { investigation: 1, awareness: 1 },
    archetypeTrainingSkill: 'technology',
    backgroundSpecialization: bgSpec('investigation', 'Archive'),
  },
  {
    key: 'medicus',
    labelDe: 'Medicus / Medica',
    playstyleDe: 'Feldmediziner unter Druck: Du stabilisierst Verletzte, bleibst wach und holst Leute aus dem Schlimmsten zurück.',
    archetype: 'healer',
    essence: 'physical',
    attributes: {
      strength: 1,
      dexterity: 2,
      endurance: 3,
      mind: 4,
      perception: 3,
      charisma: 2,
    },
    backgroundTemplateId: 'street-doctor',
    freeSkillRanks: freeRanks({
      insight: 2,
      survival: 2,
      awareness: 2,
      knowledge: 1,
    }),
    backgroundSkillPoints: { medicine: 2 },
    archetypeTrainingSkill: 'medicine',
    backgroundSpecialization: bgSpec('medicine', 'Notfallmedizin'),
  },
  {
    key: 'mystic',
    labelDe: 'Mystiker / Mystikerin',
    playstyleDe: 'Spiritueller Heiler: Du spürst Risse in Willen und Seele und stabilisierst mit Einsicht und ruhiger Präsenz.',
    archetype: 'healer',
    essence: 'spiritual',
    attributes: {
      strength: 1,
      dexterity: 2,
      endurance: 2,
      mind: 3,
      perception: 4,
      charisma: 3,
    },
    backgroundTemplateId: 'faith-order',
    freeSkillRanks: freeRanks({
      insight: 1,
      awareness: 2,
      persuasion: 2,
      knowledge: 1,
      medicine: 1,
    }),
    backgroundSkillPoints: { insight: 1, knowledge: 1 },
    archetypeTrainingSkill: 'insight',
    backgroundSpecialization: bgSpec('insight', 'Motivation'),
  },
  {
    key: 'assassin',
    labelDe: 'Assassin / Assassine',
    playstyleDe: 'Körperlicher Infiltrator: Du kommst ungesehen, schlägst zu und verschwindest über Gassen und Dächer.',
    archetype: 'rebel',
    essence: 'physical',
    attributes: {
      strength: 1,
      dexterity: 4,
      endurance: 3,
      mind: 2,
      perception: 3,
      charisma: 2,
    },
    backgroundTemplateId: 'smuggler',
    freeSkillRanks: freeRanks({
      stealth: 1,
      sleight: 2,
      acrobatics: 2,
      deception: 1,
      awareness: 1,
    }),
    backgroundSkillPoints: { stealth: 1, deception: 1 },
    archetypeTrainingSkill: 'stealth',
    backgroundSpecialization: bgSpec('stealth', 'Urbane Tarnung'),
  },
  {
    key: 'mechanom',
    labelDe: 'Mechanom',
    playstyleDe: 'Tech-Rebell aus der Werkstatt: Du sabotierst, knackst Mechanik und lässt Geräte für dich arbeiten.',
    archetype: 'rebel',
    essence: 'technological',
    attributes: {
      strength: 1,
      dexterity: 4,
      endurance: 2,
      mind: 3,
      perception: 3,
      charisma: 2,
    },
    backgroundTemplateId: 'corporate-technician',
    freeSkillRanks: freeRanks({
      sleight: 1,
      technology: 2,
      stealth: 1,
      deception: 1,
      investigation: 1,
      awareness: 1,
    }),
    backgroundSkillPoints: { technology: 1, sleight: 1 },
    archetypeTrainingSkill: 'sleight',
    backgroundSpecialization: bgSpec('technology', 'Mechanik'),
  },
  {
    key: 'mentalist',
    labelDe: 'Mentalist / Mentalistin',
    playstyleDe: 'Menschenleser und Ermittler: Du erkennst Lügen, liest Motive und drehst Gespräche leise zu deinen Gunsten.',
    archetype: 'diplomat',
    essence: 'mental',
    attributes: {
      strength: 1,
      dexterity: 2,
      endurance: 2,
      mind: 3,
      perception: 3,
      charisma: 4,
    },
    backgroundTemplateId: 'investigator',
    freeSkillRanks: freeRanks({
      insight: 1,
      persuasion: 2,
      awareness: 2,
      deception: 1,
      investigation: 1,
    }),
    backgroundSkillPoints: { insight: 1, investigation: 1 },
    archetypeTrainingSkill: 'insight',
    backgroundSpecialization: bgSpec('insight', 'Lügen erkennen'),
  },
  {
    key: 'herald',
    labelDe: 'Herold / Heroldin',
    playstyleDe: 'Öffentliche Stimme mit Mandat: Du führst mit Rede und Bühne — alle hören hin, wenn du sprichst.',
    archetype: 'diplomat',
    essence: 'bound',
    attributes: {
      strength: 1,
      dexterity: 2,
      endurance: 3,
      mind: 2,
      perception: 3,
      charisma: 4,
    },
    backgroundTemplateId: 'stage-public',
    freeSkillRanks: freeRanks({
      persuasion: 1,
      performance: 2,
      insight: 2,
      intimidation: 1,
      deception: 1,
    }),
    backgroundSkillPoints: { persuasion: 1, performance: 1 },
    archetypeTrainingSkill: 'persuasion',
    backgroundSpecialization: bgSpec('performance', 'Rede'),
  },
];
