/**
 * Contemporary Basic — 40 builtin-standard ItemDefinitions (#137).
 * Location: src/domains/items/packs/contemporary-basic.ts
 *
 * Domain-pure: no React, no Supabase, no UI imports.
 */

import type { ItemDefinition } from '../definition';
import type { ItemPack } from '../pack';
import { buildStandardItem } from './build-standard-item';

const SETTING = ['contemporary'] as const;
const TECH = 'modern' as const;

/** Exactly 40 Contemporary Basic definitions, declaration order. */
export const CONTEMPORARY_BASIC_DEFINITIONS: readonly ItemDefinition[] = Object.freeze([
  buildStandardItem({
    id: 'builtin.contemporary.smartphone',
    name: 'Smartphone',
    description: 'Alltägliches Mobiltelefon für Anrufe, Nachrichten und Apps.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['social', 'office', 'urban', 'travel'],
    capabilities: ['communicate', 'record'],
    kindKey: 'device',
    roles: ['personal'],
    basedOnDefinitionId: 'core.misc.communicator',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.laptop',
    name: 'Laptop',
    description: 'Tragbarer Computer für Arbeit, Studium und Unterhaltung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office', 'entertainment'],
    capabilities: ['record', 'research'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.misc.special-device',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.tablet',
    name: 'Tablet',
    description: 'Flaches Touch-Gerät für Lesen, Notizen und Medien.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office', 'entertainment'],
    capabilities: ['record'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.misc.documentation',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.headphones',
    name: 'Kopfhörer',
    description: 'Über-Ohr- oder In-Ear-Kopfhörer für Musik und Anrufe.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['entertainment', 'travel'],
    capabilities: ['entertain'],
    kindKey: 'device',
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.charger',
    name: 'Ladegerät',
    description: 'Netzteil und Kabel zum Laden gängiger Geräte.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'office'],
    kindKey: 'device',
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 2,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.powerbank',
    name: 'Powerbank',
    description: 'Tragbarer Akku zum Nachladen unterwegs.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'survival'],
    capabilities: ['survive'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.consumable.energy',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.wallet',
    name: 'Geldbörse',
    description: 'Kleine Börse für Karten, Ausweis und Bargeld.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['urban', 'social'],
    capabilities: ['carry'],
    roles: ['personal'],
    basedOnDefinitionId: 'core.container.pouch',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.cash',
    name: 'Bargeld',
    description: 'Scheine und Münzen für alltägliche Zahlungen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['urban', 'social'],
    capabilities: ['trade'],
    kindKey: 'currency',
    roles: ['valuable'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.bank-card',
    name: 'Bankkarte',
    description: 'Zahlungskarte für Konten und Automaten. Narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['urban', 'office'],
    capabilities: ['trade', 'access'],
    kindKey: 'currency',
    roles: ['personal'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.id-card',
    name: 'Personalausweis',
    description: 'Amtlicher Identitätsnachweis. Narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['urban', 'office'],
    capabilities: ['access'],
    kindKey: 'document',
    roles: ['personal', 'key-item'],
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.drivers-license',
    name: 'Führerschein',
    description: 'Berechtigung zum Führen von Kraftfahrzeugen. Narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'urban'],
    capabilities: ['access'],
    kindKey: 'document',
    roles: ['personal', 'key-item'],
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.keyring',
    name: 'Schlüsselbund',
    description: 'Haus-, Büro- und Nebenschlüssel an einem Ring.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['domestic', 'urban'],
    capabilities: ['unlock', 'access'],
    kindKey: 'key',
    roles: ['personal', 'key-item'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.key-card',
    name: 'Schlüsselkarte',
    description: 'Magnet- oder Chipkarte für Türen und Zutritt.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office', 'urban'],
    capabilities: ['access', 'unlock'],
    kindKey: 'key',
    roles: ['key-item'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.backpack',
    name: 'Rucksack',
    description: 'Alltagsrucksack für Schule, Pendeln und Reisen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'urban'],
    capabilities: ['carry'],
    basedOnDefinitionId: 'core.container.backpack',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.handbag',
    name: 'Handtasche',
    description: 'Kleine Tasche für persönliche Dinge.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['social', 'urban'],
    capabilities: ['carry'],
    basedOnDefinitionId: 'core.container.bag',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.shopping-bag',
    name: 'Einkaufstasche',
    description: 'Tragetasche für Einkäufe und lose Gegenstände.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['domestic', 'urban'],
    capabilities: ['carry'],
    basedOnDefinitionId: 'core.container.bag',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.notebook',
    name: 'Notizbuch',
    description: 'Gebundenes Heft für Notizen und Skizzen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office', 'social'],
    capabilities: ['record'],
    kindKey: 'document',
    basedOnDefinitionId: 'core.misc.documentation',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.ballpoint-pen',
    name: 'Kugelschreiber',
    description: 'Alltäglicher Schreibstift. Rein narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office'],
    capabilities: ['record'],
    kindKey: 'tool',
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 5,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.document-folder',
    name: 'Dokumentenmappe',
    description: 'Mappe für Unterlagen und Ausdrucke.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office'],
    capabilities: ['carry', 'record'],
    kindKey: 'document',
    basedOnDefinitionId: 'core.misc.documentation',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.contract',
    name: 'Vertrag',
    description: 'Schriftliche Vereinbarung. Rein narrativ, ohne Kampfwerte.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office', 'social'],
    kindKey: 'document',
    roles: ['evidence', 'quest'],
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.flashlight',
    name: 'Taschenlampe',
    description: 'Batteriebetriebene Lichtquelle für dunkle Orte.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival', 'urban', 'exploration'],
    capabilities: ['illuminate'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.misc.light-source',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.lighter',
    name: 'Feuerzeug',
    description: 'Kleines Feuerzeug zum Entzünden von Flammen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival', 'domestic'],
    capabilities: ['survive'],
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 2,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.umbrella',
    name: 'Regenschirm',
    description: 'Klappbarer Schirm gegen Regen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['urban', 'travel'],
    capabilities: ['survive'],
    type: 'misc',
    load: 1,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.water-bottle',
    name: 'Wasserflasche',
    description: 'Wiederbefüllbare Flasche mit Trinkwasser.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'sports', 'survival'],
    capabilities: ['consume', 'survive'],
    kindKey: 'food',
    basedOnDefinitionId: 'core.consumable.ration',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.coffee-cup',
    name: 'Kaffeebecher',
    description: 'To-go-Becher für Heißgetränke. Rein narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office', 'social', 'domestic'],
    capabilities: ['consume'],
    kindKey: 'food',
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.groceries',
    name: 'Lebensmittel',
    description: 'Alltägliche Nahrungsmittel für Haushalt und Pause.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['domestic', 'survival'],
    capabilities: ['consume'],
    kindKey: 'food',
    basedOnDefinitionId: 'core.consumable.ration',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.kitchen-knife',
    name: 'Küchenmesser',
    description: 'Alltagsmesser für die Küche — kein Kampffokus.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['domestic'],
    kindKey: 'tool',
    type: 'tool',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.first-aid-kit',
    name: 'Erste-Hilfe-Set',
    description: 'Pflaster, Verbände und Desinfektion für kleine Notfälle.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['medical', 'sports', 'survival'],
    capabilities: ['heal'],
    kindKey: 'medical',
    basedOnDefinitionId: 'core.tool.medical',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.medication',
    name: 'Medikamente',
    description: 'Allgemeine Tabletten oder Tropfen. Verbrauch; Wirkung szenenabhängig.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['medical', 'domestic'],
    capabilities: ['heal', 'consume'],
    kindKey: 'medical',
    basedOnDefinitionId: 'core.consumable.medical',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.toolbox',
    name: 'Werkzeugkoffer',
    description: 'Kasten mit Schraubenziehern, Zange und Hammern.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering', 'domestic'],
    capabilities: ['repair'],
    basedOnDefinitionId: 'core.tool.craft',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.duct-tape',
    name: 'Klebeband',
    description: 'Stabiles Gewebeband für provisorische Reparaturen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering', 'survival'],
    capabilities: ['repair', 'consume'],
    kindKey: 'resource',
    basedOnDefinitionId: 'core.consumable.repair',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.work-gloves',
    name: 'Arbeitshandschuhe',
    description: 'Schutzhandschuhe für Werkstatt und Baustelle.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering'],
    kindKey: 'clothing',
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.work-clothes',
    name: 'Arbeitskleidung',
    description: 'Robuste Kleidung für körperliche Arbeit.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering', 'domestic'],
    kindKey: 'clothing',
    type: 'misc',
    load: 1,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.bike-helmet',
    name: 'Fahrradhelm',
    description: 'Kopfschutz für Radfahren und ähnliche Aktivitäten.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['sports', 'travel', 'urban'],
    kindKey: 'clothing',
    basedOnDefinitionId: 'core.misc.headgear',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.transit-ticket',
    name: 'Fahrkarte',
    description: 'Ticket für Bus, Bahn oder vergleichbaren Nahverkehr. Narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'urban'],
    capabilities: ['access'],
    kindKey: 'document',
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 5,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.car-keys',
    name: 'Autoschlüssel',
    description: 'Schlüssel oder Funköffner für ein Fahrzeug.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'urban'],
    capabilities: ['access', 'unlock'],
    kindKey: 'key',
    roles: ['personal', 'key-item'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.soccer-ball',
    name: 'Fußball',
    description: 'Ball für Training und Spiel. Rein narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['sports', 'entertainment'],
    capabilities: ['entertain'],
    kindKey: 'sport',
    type: 'misc',
    load: 1,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.whistle',
    name: 'Trillerpfeife',
    description: 'Pfeife für Schiedsrichter, Training oder Aufmerksamkeit.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['sports'],
    capabilities: ['communicate'],
    kindKey: 'sport',
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.contemporary.sports-bag',
    name: 'Sporttasche',
    description: 'Tasche für Sportkleidung und Trainingszeug.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['sports', 'travel'],
    capabilities: ['carry'],
    kindKey: 'sport',
    basedOnDefinitionId: 'core.container.bag',
  }),
  buildStandardItem({
    id: 'builtin.contemporary.guitar',
    name: 'Gitarre',
    description: 'Akustik- oder Elektrogitarre für Unterhaltung. Rein narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['entertainment', 'social'],
    capabilities: ['entertain'],
    kindKey: 'entertainment',
    type: 'misc',
    load: 2,
    cost: 3,
    stackLimit: 1,
  }),
]);

/** Base pack: Contemporary Basic (exactly 40 definitions). */
export const CONTEMPORARY_BASIC_PACK: ItemPack = Object.freeze({
  id: 'builtin:contemporary-basic',
  version: 1,
  name: 'Contemporary Basic',
  description:
    'Kuratierter markenfreier Gegenwarts-Startkatalog: Alltag, Büro, Familie, Sport und Stadt.',
  settingTags: SETTING,
  definitionIds: Object.freeze(CONTEMPORARY_BASIC_DEFINITIONS.map((d) => d.id)),
});
