/**
 * Fantasy Basic — 40 builtin-standard ItemDefinitions (#137).
 * Location: src/domains/items/packs/fantasy-basic.ts
 *
 * Domain-pure: no React, no Supabase, no UI imports.
 */

import type { ItemDefinition } from '../definition';
import type { ItemPack } from '../pack';
import { buildStandardItem } from './build-standard-item';

const SETTING = ['fantasy'] as const;
const TECH = 'medieval' as const;

/** Exactly 40 Fantasy Basic definitions, declaration order. */
export const FANTASY_BASIC_DEFINITIONS: readonly ItemDefinition[] = Object.freeze([
  buildStandardItem({
    id: 'builtin.fantasy.longsword',
    name: 'Langschwert',
    description: 'Ausgewogenes Einhandschwert für den regulären Nahkampf.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.standard-melee',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.shortsword',
    name: 'Kurzschwert',
    description: 'Leichte Klinge für enge Räume und schnelle Stöße.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.light-melee',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.dagger',
    name: 'Dolch',
    description: 'Kurze Stichwaffe, leicht zu verbergen und im Nahkampf nützlich.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.light-melee',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.battle-axe',
    name: 'Streitaxt',
    description: 'Einhandaxt mit genug Wucht für den regulären Nahkampf.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.standard-melee',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.warhammer',
    name: 'Kriegshammer',
    description: 'Zweihändiger Hammer mit hoher Wucht gegen gepanzerte Gegner.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.heavy-melee',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.spear',
    name: 'Speer',
    description: 'Stangenwaffe mit verlängerter Reichweite im Nahkampf.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.reach-melee',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.quarterstaff',
    name: 'Kampfstab',
    description: 'Zweihändiger Holzstab mit Reichweite; vielseitig und unauffällig.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.reach-melee',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.shortbow',
    name: 'Kurzbogen',
    description: 'Kompakter Bogen für kurze bis mittlere Distanz.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.light-ranged',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.longbow',
    name: 'Langbogen',
    description: 'Klassischer Fernkampfbogen für den typischen Schusswechsel.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.standard-ranged',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.crossbow',
    name: 'Armbrust',
    description: 'Schwere Fernkampfwaffe mit hoher Durchschlagskraft; braucht beide Hände.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.heavy-ranged',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.arrows',
    name: 'Pfeile',
    description: 'Gebündelte Pfeile als Verbrauch für Bogenwaffen. Kein eigener Schaden.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    kindKey: 'resource',
    basedOnDefinitionId: 'core.consumable.general',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.bolts',
    name: 'Bolzen',
    description: 'Armbrustbolzen als Verbrauch. Kein eigener Schaden.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    kindKey: 'resource',
    basedOnDefinitionId: 'core.consumable.general',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.light-shield',
    name: 'leichter Schild',
    description: 'Tragbarer Holz- oder Lederschild für eine Hand.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['defend'],
    basedOnDefinitionId: 'core.shield.standard',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.leather-armor',
    name: 'Lederharnisch',
    description: 'Leichter Körperschutz aus gehärtetem Leder ohne starke Einschränkung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['defend'],
    basedOnDefinitionId: 'core.armor.light',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.chainmail',
    name: 'Kettenhemd',
    description: 'Mittlerer Körperschutz aus verschlungenen Ringen; braucht etwas Kraft.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['defend'],
    basedOnDefinitionId: 'core.armor.medium',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.plate-armor',
    name: 'Plattenrüstung',
    description: 'Schwerer Metallschutz mit maximalem Kern-Schutz; nur mit genug Stärke.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['defend'],
    basedOnDefinitionId: 'core.armor.heavy',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.healing-potion',
    name: 'Heiltrank',
    description: 'Trank für medizinische Szenen. Konkrete Wirkung legt Weltprofil oder Fähigkeit fest.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['medical', 'survival'],
    capabilities: ['heal', 'consume'],
    kindKey: 'medical',
    basedOnDefinitionId: 'core.consumable.medical',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.antidote',
    name: 'Gegengift',
    description: 'Mittel gegen Gifte und Toxine. Verbrauch; Wirkung ist szenenabhängig.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['medical'],
    capabilities: ['heal', 'consume'],
    kindKey: 'medical',
    basedOnDefinitionId: 'core.consumable.medical',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.travel-rations',
    name: 'Reiseproviant',
    description: 'Getrocknete Nahrung für unterwegs. Verbrauchen reduziert die Menge um 1.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival', 'travel'],
    capabilities: ['consume', 'survive'],
    kindKey: 'food',
    basedOnDefinitionId: 'core.consumable.ration',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.waterskin',
    name: 'Wasserschlauch',
    description: 'Gefüllter Schlauch mit Trinkwasser für die Reise.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival', 'travel'],
    capabilities: ['consume', 'survive'],
    kindKey: 'food',
    basedOnDefinitionId: 'core.consumable.ration',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.torch',
    name: 'Fackel',
    description: 'Pechgetränkte Fackel für dunkle Gänge und Höhlen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['exploration', 'survival'],
    capabilities: ['illuminate'],
    basedOnDefinitionId: 'core.misc.light-source',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.lantern',
    name: 'Laterne',
    description: 'Geschützte Öllaterne; zuverlässiger als eine offene Fackel.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['exploration', 'survival'],
    capabilities: ['illuminate'],
    basedOnDefinitionId: 'core.misc.light-source',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.rope',
    name: 'Seil',
    description: 'Hanfseil zum Klettern, Sichern und Ziehen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['exploration', 'survival'],
    capabilities: ['survive'],
    basedOnDefinitionId: 'core.misc.rope',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.grappling-hook',
    name: 'Enterhaken',
    description: 'Haken mit Seilanschluss für Kletter- und Entermanöver.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['exploration'],
    capabilities: ['survive'],
    basedOnDefinitionId: 'core.tool.climbing',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.backpack',
    name: 'Rucksack',
    description: 'Lederner Reiserucksack mit Platz für Ausrüstung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'survival'],
    capabilities: ['carry'],
    basedOnDefinitionId: 'core.container.backpack',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.belt-pouch',
    name: 'Gürteltasche',
    description: 'Kleine Tasche am Gürtel für Münzen und Kleinteile.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel'],
    capabilities: ['carry'],
    basedOnDefinitionId: 'core.container.pouch',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.lockpicks',
    name: 'Dietrichset',
    description: 'Feine Stifte und Haken zum Öffnen einfacher Schlösser.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['exploration', 'urban'],
    capabilities: ['unlock'],
    basedOnDefinitionId: 'core.tool.precision',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.healer-kit',
    name: 'Heilerset',
    description: 'Verbände, Salben und Nadeln für Feldversorgung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['medical'],
    capabilities: ['heal'],
    kindKey: 'medical',
    basedOnDefinitionId: 'core.tool.medical',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.craftsman-tools',
    name: 'Handwerkszeug',
    description: 'Hammer, Zange und Feilen für Reparatur und Fertigung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering'],
    capabilities: ['repair'],
    basedOnDefinitionId: 'core.tool.craft',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.map',
    name: 'Karte',
    description: 'Handgezeichnete Gebietskarte zur Orientierung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'exploration'],
    capabilities: ['navigate'],
    basedOnDefinitionId: 'core.tool.navigation',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.compass',
    name: 'Kompass',
    description: 'Magnetnadel zur Himmelsrichtungsbestimmung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'exploration'],
    capabilities: ['navigate'],
    basedOnDefinitionId: 'core.tool.navigation',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.writing-kit',
    name: 'Schreibzeug',
    description: 'Feder, Tinte und Pergament zum Festhalten von Notizen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['social', 'office'],
    capabilities: ['record'],
    kindKey: 'document',
    basedOnDefinitionId: 'core.misc.documentation',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.sealed-letter',
    name: 'versiegelter Brief',
    description: 'Verschlossenes Schreiben mit Wachssiegel. Rein narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['social'],
    roles: ['quest', 'evidence'],
    kindKey: 'document',
    type: 'misc',
    load: 0,
    cost: 0,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.fantasy.book',
    name: 'Buch',
    description: 'Gebundenes Werk mit Wissen, Geschichten oder Ritualnotizen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['science', 'entertainment'],
    capabilities: ['research'],
    kindKey: 'document',
    basedOnDefinitionId: 'core.misc.documentation',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.keyring',
    name: 'Schlüsselbund',
    description: 'Mehrere Schlüssel an einem Ring. Öffnet passende Schlösser narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['urban', 'domestic'],
    capabilities: ['unlock', 'access'],
    kindKey: 'key',
    roles: ['key-item'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.fantasy.coin-purse',
    name: 'Münzbeutel',
    description: 'Kleiner Beutel mit Münzen für Handel und Bestechung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['social', 'urban'],
    capabilities: ['trade'],
    kindKey: 'currency',
    roles: ['valuable'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.fantasy.gemstone',
    name: 'Edelstein',
    description: 'Geschliffener Stein von spürbarem Wert. Rein narrativ/wertvoll.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['social'],
    capabilities: ['trade'],
    kindKey: 'resource',
    roles: ['valuable', 'collectible'],
    type: 'misc',
    load: 0,
    cost: 3,
    stackLimit: 5,
  }),
  buildStandardItem({
    id: 'builtin.fantasy.blanket',
    name: 'Decke',
    description: 'Wolldecke gegen Kälte bei Nachtlagern.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival', 'domestic'],
    capabilities: ['survive'],
    basedOnDefinitionId: 'core.tool.survival',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.tinderbox',
    name: 'Zunderzeug',
    description: 'Feuerstein, Stahl und Zunder zum Entfachen von Flammen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival'],
    capabilities: ['survive', 'illuminate'],
    basedOnDefinitionId: 'core.tool.survival',
  }),
  buildStandardItem({
    id: 'builtin.fantasy.musical-instrument',
    name: 'Musikinstrument',
    description: 'Tragbares Instrument für Unterhaltung und soziale Szenen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['entertainment', 'social'],
    capabilities: ['entertain'],
    kindKey: 'entertainment',
    type: 'misc',
    load: 1,
    cost: 2,
    stackLimit: 1,
  }),
]);

/** Base pack: Fantasy Basic (exactly 40 definitions). */
export const FANTASY_BASIC_PACK: ItemPack = Object.freeze({
  id: 'builtin:fantasy-basic',
  version: 1,
  name: 'Fantasy Basic',
  description:
    'Kuratierter markenfreier Fantasy-Startkatalog: Waffen, Rüstung, Reise- und Alltagsgegenstände.',
  settingTags: SETTING,
  definitionIds: Object.freeze(FANTASY_BASIC_DEFINITIONS.map((d) => d.id)),
});
