/**
 * Sci-Fi Basic — 40 builtin-standard ItemDefinitions (#137).
 * Location: src/domains/items/packs/scifi-basic.ts
 *
 * Domain-pure: no React, no Supabase, no UI imports.
 */

import type { ItemDefinition } from '../definition';
import type { ItemPack } from '../pack';
import { buildStandardItem } from './build-standard-item';

const SETTING = ['sci-fi'] as const;
const TECH = 'advanced' as const;

/** Exactly 40 Sci-Fi Basic definitions, declaration order. */
export const SCIFI_BASIC_DEFINITIONS: readonly ItemDefinition[] = Object.freeze([
  buildStandardItem({
    id: 'builtin.scifi.compact-energy-weapon',
    name: 'kompakte Energiewaffe',
    description: 'Handliche Energiewaffe für kurze bis mittlere Distanz.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.light-ranged',
  }),
  buildStandardItem({
    id: 'builtin.scifi.standard-energy-weapon',
    name: 'Standard-Energiewaffe',
    description: 'Reguläre Seitenwaffe für den typischen Feuerkampf.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.standard-ranged',
  }),
  buildStandardItem({
    id: 'builtin.scifi.heavy-energy-rifle',
    name: 'schweres Energiegewehr',
    description: 'Zweihändige Energiewaffe mit hoher Durchschlagskraft.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.heavy-ranged',
  }),
  buildStandardItem({
    id: 'builtin.scifi.stun-device',
    name: 'Betäubungsgerät',
    description: 'Nichttödliche Nah- oder Fernkampfwaffe zum Ausschalten ohne tödlichen Schaden.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat', 'urban'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.light-ranged',
  }),
  buildStandardItem({
    id: 'builtin.scifi.energy-blade',
    name: 'Energieklinge',
    description: 'Nahkampfwaffe mit energiegeladenem Schneidefeld.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['attack'],
    basedOnDefinitionId: 'core.weapon.standard-melee',
  }),
  buildStandardItem({
    id: 'builtin.scifi.light-protective-suit',
    name: 'leichter Schutzanzug',
    description: 'Flexible Schutzschicht ohne starke Bewegungseinschränkung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['defend'],
    kindKey: 'armor',
    basedOnDefinitionId: 'core.armor.light',
  }),
  buildStandardItem({
    id: 'builtin.scifi.tactical-protective-suit',
    name: 'taktischer Schutzanzug',
    description: 'Ausgewogener Körperschutz für Einsatzteams; braucht etwas Kraft.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['defend'],
    kindKey: 'armor',
    basedOnDefinitionId: 'core.armor.medium',
  }),
  buildStandardItem({
    id: 'builtin.scifi.heavy-protective-suit',
    name: 'schwerer Schutzanzug',
    description: 'Schwerer Einsatzanzug mit maximalem Kern-Schutz.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['defend'],
    kindKey: 'armor',
    basedOnDefinitionId: 'core.armor.heavy',
  }),
  buildStandardItem({
    id: 'builtin.scifi.personal-shield-emitter',
    name: 'persönlicher Schildemitter',
    description: 'Tragbarer Emitter, der wie ein Schild eine Hand belegt.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['defend'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.shield.standard',
  }),
  buildStandardItem({
    id: 'builtin.scifi.energy-cell',
    name: 'Energiezelle',
    description: 'Austauschbare Zelle als Betriebsmittel für Geräte und Waffen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering', 'survival'],
    capabilities: ['consume'],
    kindKey: 'resource',
    basedOnDefinitionId: 'core.consumable.energy',
  }),
  buildStandardItem({
    id: 'builtin.scifi.ammo-pack',
    name: 'Munitionspack',
    description: 'Nachladepack für Energiewaffen. Kein eigener Schaden.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['combat'],
    capabilities: ['consume'],
    kindKey: 'resource',
    basedOnDefinitionId: 'core.consumable.general',
  }),
  buildStandardItem({
    id: 'builtin.scifi.medkit',
    name: 'Medkit',
    description: 'Kompaktes medizinisches Set für Feldversorgung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['medical'],
    capabilities: ['heal'],
    kindKey: 'medical',
    basedOnDefinitionId: 'core.tool.medical',
  }),
  buildStandardItem({
    id: 'builtin.scifi.hypospray',
    name: 'Hypospray',
    description: 'Injizierbarer medizinischer Verbrauch für Akutbehandlung.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['medical'],
    capabilities: ['heal', 'consume'],
    kindKey: 'medical',
    basedOnDefinitionId: 'core.consumable.medical',
  }),
  buildStandardItem({
    id: 'builtin.scifi.antitoxin',
    name: 'Antitoxin',
    description: 'Gegenmittel gegen Toxine und Biogifte. Verbrauch.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['medical'],
    capabilities: ['heal', 'consume'],
    kindKey: 'medical',
    basedOnDefinitionId: 'core.consumable.medical',
  }),
  buildStandardItem({
    id: 'builtin.scifi.emergency-ration',
    name: 'Notration',
    description: 'Komprimierte Nahrung für Notlagen und lange Missionen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival', 'travel'],
    capabilities: ['consume', 'survive'],
    kindKey: 'food',
    basedOnDefinitionId: 'core.consumable.ration',
  }),
  buildStandardItem({
    id: 'builtin.scifi.water-purifier',
    name: 'Wasseraufbereiter',
    description: 'Kleines Gerät zur Aufbereitung von Trinkwasser vor Ort.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival'],
    capabilities: ['survive'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.tool.survival',
  }),
  buildStandardItem({
    id: 'builtin.scifi.communicator',
    name: 'Kommunikator',
    description: 'Tragbares Gerät zur Kommunikation über Distanz.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['social', 'travel'],
    capabilities: ['communicate'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.misc.communicator',
  }),
  buildStandardItem({
    id: 'builtin.scifi.datapad',
    name: 'Datapad',
    description: 'Tragbarer Datenleser und Notizgerät.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['office', 'science'],
    capabilities: ['record', 'research'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.misc.documentation',
  }),
  buildStandardItem({
    id: 'builtin.scifi.hand-scanner',
    name: 'Handscanner',
    description: 'Kompakter Scanner für Oberflächen und einfache Messungen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['science', 'exploration'],
    capabilities: ['scan', 'research'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.tool.research',
  }),
  buildStandardItem({
    id: 'builtin.scifi.multi-scanner',
    name: 'Multiscanner',
    description: 'Vielseitiges Analysegerät für Umwelt, Material und Biozeichen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['science', 'exploration'],
    capabilities: ['scan', 'research'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.tool.research',
  }),
  buildStandardItem({
    id: 'builtin.scifi.navigation-module',
    name: 'Navigationsmodul',
    description: 'Modul zur Orientierung und Routenplanung in unbekanntem Terrain.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'exploration'],
    capabilities: ['navigate'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.tool.navigation',
  }),
  buildStandardItem({
    id: 'builtin.scifi.engineering-kit',
    name: 'Engineering-Kit',
    description: 'Werkzeugsatz für Wartung und Feldreparaturen an Technik.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering'],
    capabilities: ['repair'],
    basedOnDefinitionId: 'core.tool.repair',
  }),
  buildStandardItem({
    id: 'builtin.scifi.precision-tools',
    name: 'Präzisionswerkzeug',
    description: 'Feine Werkzeuge für Elektronik und filigrane Arbeit.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering'],
    capabilities: ['repair'],
    basedOnDefinitionId: 'core.tool.precision',
  }),
  buildStandardItem({
    id: 'builtin.scifi.repair-material',
    name: 'Reparaturmaterial',
    description: 'Verbrauchsteile und Dichtmittel für Reparaturen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering'],
    capabilities: ['repair', 'consume'],
    kindKey: 'resource',
    basedOnDefinitionId: 'core.consumable.repair',
  }),
  buildStandardItem({
    id: 'builtin.scifi.research-kit',
    name: 'Forschungskit',
    description: 'Instrumente und Probenträger für Labor- und Feldanalyse.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['science'],
    capabilities: ['research'],
    basedOnDefinitionId: 'core.tool.research',
  }),
  buildStandardItem({
    id: 'builtin.scifi.sample-container',
    name: 'Probenbehälter',
    description: 'Versiegelbarer Behälter für Proben und Empfindliches.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['science'],
    capabilities: ['carry', 'research'],
    basedOnDefinitionId: 'core.container.pouch',
  }),
  buildStandardItem({
    id: 'builtin.scifi.flashlight',
    name: 'Taschenlampe',
    description: 'Kompakte Lichtquelle für dunkle Korridore und Außenarbeiten.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['exploration', 'survival'],
    capabilities: ['illuminate'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.misc.light-source',
  }),
  buildStandardItem({
    id: 'builtin.scifi.multitool',
    name: 'Multitool',
    description: 'Kombiniertes Handwerkzeug für alltägliche technische Aufgaben.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering', 'survival'],
    capabilities: ['repair'],
    basedOnDefinitionId: 'core.tool.craft',
  }),
  buildStandardItem({
    id: 'builtin.scifi.access-card',
    name: 'Zugangskarte',
    description: 'Berechtigungskarte für Türen und Terminals. Narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['urban', 'office'],
    capabilities: ['access', 'unlock'],
    kindKey: 'key',
    roles: ['key-item'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.scifi.identity-module',
    name: 'Identitätsmodul',
    description: 'Persönliches Identifikationsmodul für Zugang und Nachweis.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['urban', 'social'],
    capabilities: ['access'],
    kindKey: 'key',
    roles: ['personal', 'key-item'],
    type: 'misc',
    load: 0,
    cost: 2,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.scifi.data-chip',
    name: 'Datenchip',
    description: 'Kleiner Datenträger für Dateien und Logs.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['science', 'office'],
    capabilities: ['record'],
    kindKey: 'document',
    basedOnDefinitionId: 'core.misc.documentation',
  }),
  buildStandardItem({
    id: 'builtin.scifi.encrypted-file',
    name: 'verschlüsselte Datei',
    description: 'Geschützte Datenablage. Inhalt und Schlüssel sind narrativ.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['science', 'social'],
    capabilities: ['record'],
    kindKey: 'document',
    roles: ['evidence', 'quest'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.scifi.credits',
    name: 'Credits',
    description: 'Digitale oder physische Zahlungseinheit für Handel.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['social', 'urban'],
    capabilities: ['trade'],
    kindKey: 'currency',
    roles: ['valuable'],
    type: 'misc',
    load: 0,
    cost: 1,
    stackLimit: 1,
  }),
  buildStandardItem({
    id: 'builtin.scifi.universal-backpack',
    name: 'Universalrucksack',
    description: 'Modularer Rucksack für Mission und Alltag.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['travel', 'survival'],
    capabilities: ['carry'],
    basedOnDefinitionId: 'core.container.backpack',
  }),
  buildStandardItem({
    id: 'builtin.scifi.equipment-bag',
    name: 'Ausrüstungstasche',
    description: 'Robuste Tasche für Werkzeug und Einsatzmaterial.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering', 'travel'],
    capabilities: ['carry'],
    basedOnDefinitionId: 'core.container.bag',
  }),
  buildStandardItem({
    id: 'builtin.scifi.spacesuit',
    name: 'Raumanzug',
    description: 'Druckanzug für Außenbordeinsätze und luftlose Umgebungen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival', 'exploration'],
    capabilities: ['survive', 'defend'],
    kindKey: 'clothing',
    basedOnDefinitionId: 'core.armor.medium',
  }),
  buildStandardItem({
    id: 'builtin.scifi.breathing-apparatus',
    name: 'Atemgerät',
    description: 'Tragbares Atemsystem für toxische oder dünne Atmosphären.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival'],
    capabilities: ['survive'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.tool.survival',
  }),
  buildStandardItem({
    id: 'builtin.scifi.signal-beacon',
    name: 'Signalgeber',
    description: 'Notfallbake zum Aussenden von Ortungs- und Hilfsignalen.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['survival', 'travel'],
    capabilities: ['communicate', 'survive'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.misc.special-device',
  }),
  buildStandardItem({
    id: 'builtin.scifi.cable-tether',
    name: 'Kabel/Leine',
    description: 'Sicherungsleine oder Daten-/Energiekabel für Arbeit und EVA.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering', 'survival'],
    capabilities: ['survive'],
    basedOnDefinitionId: 'core.misc.rope',
  }),
  buildStandardItem({
    id: 'builtin.scifi.portable-energy-pack',
    name: 'tragbarer Energiepack',
    description: 'Mobiler Energiespeicher für Geräte und Notstrom.',
    settingTags: SETTING,
    techLevel: TECH,
    contexts: ['engineering', 'survival'],
    capabilities: ['survive'],
    kindKey: 'device',
    basedOnDefinitionId: 'core.consumable.energy',
  }),
]);

/** Base pack: Sci-Fi Basic (exactly 40 definitions). */
export const SCIFI_BASIC_PACK: ItemPack = Object.freeze({
  id: 'builtin:scifi-basic',
  version: 1,
  name: 'Sci-Fi Basic',
  description:
    'Kuratierter markenfreier Science-Fiction-Startkatalog: Energieausrüstung, Medizin, Technik und Raumfahrt.',
  settingTags: SETTING,
  definitionIds: Object.freeze(SCIFI_BASIC_DEFINITIONS.map((d) => d.id)),
});
